### ISSUE TITLE
Polishing TODO

### ISSUE THREAD

**Issue by noandrea** [apeunit/LaunchControlCenter#2]
**Add Event**

- [x] add cancel button (but ask for confirmation)    

**Event list**

- [x]  remove event ID    
- [x] format the Start date, add if the event is live or not»    

**Event Details**
- [x] display accounts as they are shown in the event creation
